[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  included_files = ["database/database.sqlite"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200


